"""Add article model

Revision ID: 6dd7db6af726
Revises: 
Create Date: 2021-03-07 09:14:04.418596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd7db6af726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('drafted', sa.Boolean(), nullable=True))
    op.add_column('article', sa.Column('image', sa.UnicodeText(), nullable=True))
    op.add_column('article', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'updated_at')
    op.drop_column('article', 'image')
    op.drop_column('article', 'drafted')
    op.drop_column('article', 'created_at')
    # ### end Alembic commands ###
