"""Add article.slug column

Revision ID: 9be9eff34387
Revises: 6dd7db6af726
Create Date: 2021-03-07 12:03:56.366580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be9eff34387'
down_revision = '6dd7db6af726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
